/**
 * Per-route document metadata.
 *
 * Hash routes never trigger a document load, so without this every page reports
 * the home page's title and description — including to agents and preview
 * fetchers that do run JavaScript. The static half of the story (JSON-LD,
 * noscript, llms.txt) is generated by `scripts/generate-agent-context.mjs`.
 */

import { teamBySlug } from '@/data/useCases';
import { CATALOG_LABEL } from '@/data/integrations';
import { findIntegration } from '@/data/integrationDetail';
import { resourcePages, type ResourceKind } from '@/data/resources';

const SITE_NAME = 'Kentron AI';

const HOME = {
  title: 'Kentron AI — an AI coworker that proves what it did',
  description:
    'Deploy agentic AI at scale with complete confidence. One platform. Unified governance. Real-time compliance. Proof of every decision.',
};

interface Meta {
  title: string;
  description: string;
  /** Kept off search results and out of link previews. Internal pages only. */
  noindex?: boolean;
}

function metaFor(name: string, slug: string): Meta {
  switch (name) {
    case 'use-cases':
      return {
        title: `Use cases — ${SITE_NAME}`,
        description: 'Worked examples of what Kentron AI runs for engineering, security, finance, and support teams.',
      };
    case 'use-case': {
      const team = teamBySlug.get(slug);
      if (!team) break;
      return { title: `${team.label} use cases — ${SITE_NAME}`, description: team.intro };
    }
    case 'integrations':
      return {
        title: `Integrations — ${SITE_NAME}`,
        description: `Browse ${CATALOG_LABEL} connectors Kentron AI can drive, from AWS and GitHub to Slack and Salesforce.`,
      };
    case 'integration': {
      const tool = findIntegration(slug);
      if (!tool) break;
      return {
        title: `${tool.name} integration — ${SITE_NAME}`,
        description: `Connect ${tool.name} to Kentron AI: what it can read, what it can change, and what each run leaves behind in the receipt chain.`,
      };
    }
    case 'pricing':
      return {
        title: `Pricing — ${SITE_NAME}`,
        description: 'Credit-based pricing that starts free and scales with what your agents actually run.',
      };
    case 'security':
      return {
        title: `Security — ${SITE_NAME}`,
        description:
          'Sandbox isolation, org-level policy gates, and an immutable receipt chain you can verify without trusting our infrastructure.',
      };
    case 'resource': {
      const page = resourcePages[slug as ResourceKind];
      if (!page) break;
      return { title: `${page.eyebrow} — ${SITE_NAME}`, description: page.lead };
    }
    case 'admin':
      // The title the console carried as a site of its own. An internal tool has
      // nothing to gain from being found, so it is also the one route here that
      // asks not to be indexed, and its description says no more than the name
      // already implies.
      return {
        title: `${SITE_NAME} — Internal Console`,
        description: 'Internal tool for the Kentron AI team. Sign-in required.',
        noindex: true,
      };
  }
  return HOME;
}

function setTag(selector: string, attr: string, value: string) {
  const el = document.head.querySelector(selector);
  if (el) el.setAttribute(attr, value);
}

/**
 * index.html carries no robots tag, because every public page wants the
 * default. One is created on demand for the pages that do not, and set back to
 * `index` on the way out rather than removed — a crawler that arrives mid-route
 * should never read a stale `noindex`.
 */
function setRobots(noindex: boolean) {
  let el = document.head.querySelector('meta[name="robots"]');
  if (!el) {
    if (!noindex) return;
    el = document.createElement('meta');
    el.setAttribute('name', 'robots');
    document.head.appendChild(el);
  }
  el.setAttribute('content', noindex ? 'noindex, nofollow, noarchive' : 'index, follow');
}

export function applyRouteMeta(name: string, slug: string) {
  const { title, description, noindex } = metaFor(name, slug);
  const canonical = `${window.location.origin}${window.location.pathname}${window.location.hash}`;

  document.title = title;
  setTag('meta[name="description"]', 'content', description);
  setTag('meta[property="og:title"]', 'content', title);
  setTag('meta[property="og:description"]', 'content', description);
  setTag('meta[property="og:url"]', 'content', canonical);
  setTag('meta[name="twitter:title"]', 'content', title);
  setTag('meta[name="twitter:description"]', 'content', description);
  setTag('link[rel="canonical"]', 'href', canonical);
  setRobots(Boolean(noindex));
}
