/**
 * Per-route document metadata.
 *
 * Hash routes never trigger a document load, so without this every page reports
 * the home page's title and description — including to agents and preview
 * fetchers that do run JavaScript. The static half of the story (JSON-LD,
 * noscript, llms.txt) is generated by `scripts/generate-agent-context.mjs`.
 */

import { teamBySlug } from '@/data/useCases';
import { catalogCounts } from '@/data/integrations';
import { findIntegration } from '@/data/integrationDetail';
import { resourcePages, type ResourceKind } from '@/data/resources';

const SITE_NAME = 'Receipt';

const HOME = {
  title: 'Receipt — an AI coworker that proves what it did',
  description:
    'Your AI coworker that proves what it did. Receipt runs tasks across your SaaS apps and servers, then backs every result with a verifiable receipt.',
};

interface Meta {
  title: string;
  description: string;
}

function metaFor(name: string, slug: string): Meta {
  switch (name) {
    case 'use-cases':
      return {
        title: `Use cases — ${SITE_NAME}`,
        description: 'Worked examples of what Receipt runs for engineering, security, finance, and support teams.',
      };
    case 'use-case': {
      const team = teamBySlug.get(slug);
      if (!team) break;
      return { title: `${team.label} use cases — ${SITE_NAME}`, description: team.intro };
    }
    case 'integrations':
      return {
        title: `Integrations — ${SITE_NAME}`,
        description: `Browse ${catalogCounts.total} connectors Receipt can drive, from AWS and GitHub to Slack and Salesforce.`,
      };
    case 'integration': {
      const tool = findIntegration(slug);
      if (!tool) break;
      return {
        title: `${tool.name} integration — ${SITE_NAME}`,
        description: `Connect ${tool.name} to Receipt: what it can read, what it can change, and what each run leaves behind in the receipt chain.`,
      };
    }
    case 'pricing':
      return {
        title: `Pricing — ${SITE_NAME}`,
        description: 'Credit-based pricing that starts free and scales with what your agents actually run.',
      };
    case 'security':
      return {
        title: `Security — ${SITE_NAME}`,
        description:
          'Sandbox isolation, org-level policy gates, and an immutable receipt chain you can verify without trusting our infrastructure.',
      };
    case 'resource': {
      const page = resourcePages[slug as ResourceKind];
      if (!page) break;
      return { title: `${page.eyebrow} — ${SITE_NAME}`, description: page.lead };
    }
  }
  return HOME;
}

function setTag(selector: string, attr: string, value: string) {
  const el = document.head.querySelector(selector);
  if (el) el.setAttribute(attr, value);
}

export function applyRouteMeta(name: string, slug: string) {
  const { title, description } = metaFor(name, slug);
  const canonical = `${window.location.origin}${window.location.pathname}${window.location.hash}`;

  document.title = title;
  setTag('meta[name="description"]', 'content', description);
  setTag('meta[property="og:title"]', 'content', title);
  setTag('meta[property="og:description"]', 'content', description);
  setTag('meta[property="og:url"]', 'content', canonical);
  setTag('meta[name="twitter:title"]', 'content', title);
  setTag('meta[name="twitter:description"]', 'content', description);
  setTag('link[rel="canonical"]', 'href', canonical);
}
